`timescale 1ns / 1ps
//this checks which reservation station is empty and which is full and assigns the instruction which is waiting in the queue to that particular reservation
//station, if it is a load or store instruction it sends it to the loadstore buffer, if it recieves an instruction and one of the values is not ready
//then it just passes on the instruction to the reservation station along with a tag, which is given by the register alias table, but if both the values are ready
//it straight up forwards the two values to the reservation station, and the reservation station handles the stuff, when it gets the values along with the corresponding tag
//
//
module Dispatcher(
    input [31:0] inst,
    input queue_empty,
    output deque,// these are the inputs from the queue
    
   
    input [31:0] readData1, // so we get the information from the register file and the instruction at the same time
    input [31:0] readData2, // whatever is there in readreg1 and readreg2 is sent instantly,
    //so this doesnt wait for both of them to be ready, that is handled by the reservation
    // table, as it is written down, if rs1 is busy(from the tag) 0 is given , else the value is given normally, and the tag is sent as q1
     output [4:0] readReg1, //this and readreg2 are taken from the instruction that is given as input
    output [4:0] readReg2,  // and this recieves the input data simultaneously anyway
    
    input [31:0] imm_val, // The immediate value generated by ImmGen, it uses this since there is no readdata2 and there is no readreg2
    // the immediate value is recieved and is forwarded as V2

    
    input rs1_busy,// for deciding whether a recieved information is correct or not 
    input rs2_busy, // if busy is 0 then take info, if it is 1 then pass 0, as in the assign statement
    input [2:0] rs1_tag,
    input [2:0] rs2_tag,// these are the connections to the reservation alias table
   
    output [4:0] rd,
    output rd_issue_en,
    output [2:0] rd_tag,
    // so essentially, the dipsatcher decides which station the instruction has to go to
    //and if both the values are ready then v1 and v2 are passed, if not the corresponding tag is passed
    // and once an instruction is allocated the register which is being calculated is set as busy
    // and the reservation station number is saved as the tag
    //hence the rd_tag and the rd_issue_en
    
    input [7:1] rs_busy_status,
    output [7:1] rs_issue_en,
    output [4:0] issue_alu_ctrl,
    output [31:0] V1,// output rs1 rs2 values 
    output [31:0] V2,// these are passed as values to to the reservation station if they are valid
    output [2:0] issue_Q1,// the tags , which are passed to the reservation station when they are not ready
    output [2:0] issue_Q2,//
    output is_load, // whenever a load or store instruction comes about
    output is_store
    );
    
    wire [6:0] opcode = inst[6:0];
    assign is_load = (opcode == 7'b0000011);
     assign is_store = (opcode == 7'b0100011);
     wire is_mem = is_load||is_store; //just checks whether the opcode is a load or store instruction
     // if it is a load or store instruction it means memory should be accessed thus is_mem
     wire is_imm = (opcode == 7'b0010011) || is_load;//basically if it is a load or an immediate instruction 
     //there is no need for a second register
     //hence both are kind of immediate instruction hence is_imm whether the instruction needs an immediate
    
    
    assign readReg1 = inst[19:15];
    assign readReg2 = inst[24:20];
    assign rd = inst[11:7]; // standard r type instrcution code distribution
    // if it is a store instruction a signal will be sent inorder to ignore this particular wire
    wire [1:0] ALUOp;
    assign ALUOp = (opcode == 7'b0110011) ? 2'b10 :        //if it an rtype instruction
                   (opcode == 7'b0010011) ? 2'b11:        // i type instruction
                   (opcode == 7'b1100011) ? 2'b01: 2'b00;// branch is included to prevent crashes, and default is load store
    
    wire [4:0] decoded_alu_ctrl;
    ALUCtrl m_ALUCtrl(
            .ALUOp(ALUOp),
            .funct7_c(inst[30]),
            .funct3_c(inst[14:12]),
            .ALUCtl(decoded_alu_ctrl)
            );
            
      assign issue_alu_ctrl= decoded_alu_ctrl;
            
     
    assign rd_tag = (is_mem)? (!rs_busy_status[7] ? 3'b111 : 3'b000):// if it is a memory accessing instruction,
    // and the 7th reservation station is not busy then assign the tag to 7 else assign to 0
    (!rs_busy_status[1]) ? 3'b001 : // if this reservation station is  not busy set the tag as 001
    (!rs_busy_status[2]) ? 3'b010 : // similarly with this, if 2nd reg is busy then tg is 2
    (!rs_busy_status[3]) ? 3'b011 : // tag is 3 yada yada
    (!rs_busy_status[4]) ? 3'b100 :
    (!rs_busy_status[5]) ? 3'b101 :// so if any register is free assign the instruction to that register
    (!rs_busy_status[6]) ? 3'b110 : 3'b000;
    
    wire issue_en = (!queue_empty && rd_tag != 3'b000);
    assign rd_issue_en = (issue_en) && !is_store; // if the queue is not empty and the 
    // tag is not 0 then 1, else it is 0
    assign deque = (issue_en) ? 1'b1 : 1'b0;
    // same shi
    
    assign rs_issue_en[1] = (issue_en) && (rd_tag==1);
    assign rs_issue_en[2] = (issue_en) && (rd_tag==2);
    assign rs_issue_en[3] = (issue_en) && (rd_tag==3);
    assign rs_issue_en[4] = (issue_en) && (rd_tag==4);
    assign rs_issue_en[5] = (issue_en) && (rd_tag==5);
    assign rs_issue_en[6] = (issue_en) && (rd_tag==6);
    assign rs_issue_en[7] = (issue_en) && (rd_tag==7);// this takes the instruction to the load store buffer
    // turns on the only wire for the station we have chose
    // like if rd_tag =3 then 0000100
    // if rd_tag = 5 then 0010000 etc etc chill only
    
    
   
    assign issue_Q1 = (rs1_busy) ? rs1_tag : 0;
    assign V1 = (rs1_busy) ? 0 : readData1;
    
    // If it's an immediate instruction, Q2 is 0 (ready) and V2 gets the immediate value
    assign issue_Q2 = (is_imm) ? 3'b0 : ((rs2_busy) ? rs2_tag : 0);
    assign V2 = (is_imm) ? imm_val : ((rs2_busy) ? 0 : readData2);

endmodule
